# Generated by Django 3.1.3 on 2020-11-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название инвентаря')),
                ('description', models.TextField(verbose_name='Описание предмета инвентаря')),
                ('availability', models.BooleanField(verbose_name='доступность')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название организации')),
                ('description', models.TextField(verbose_name='Описание')),
                ('mission', models.TextField(verbose_name='Миссия')),
                ('motivation', models.TextField(verbose_name='Мотивировка')),
                ('work_trajectory', models.TextField(verbose_name='Траектория работы')),
                ('goal', models.TextField(verbose_name='Цель')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название мероприятия')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('organization', models.ManyToManyField(to='api.Organization', verbose_name='Организатор мероприятия')),
            ],
        ),
    ]
