# Generated by Django 3.1.3 on 2020-12-12 05:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_end',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата окончания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='level',
            field=models.CharField(choices=[('international', 'Международный'), ('country', 'Всероссийский'), ('regional', 'Региональный'), ('university', 'Университетский')], default='university', max_length=64, verbose_name='Уровень мероприятия'),
        ),
    ]
