# Generated by Django 3.1.3 on 2021-01-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201212_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorganizators',
            name='grant',
            field=models.PositiveSmallIntegerField(default=123, verbose_name='стипендия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventorganizators',
            name='role',
            field=models.CharField(blank=True, choices=[('leader', 'Руководитель'), ('manager', 'Организатор'), ('executor', 'Исполнитель'), ('volonteer', 'волонтер')], default='volonteer', max_length=64, null=True, verbose_name='Роль участника'),
        ),
    ]
