# Generated by Django 3.1.3 on 2021-01-25 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210106_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='auditorium',
            field=models.CharField(default='B8080', max_length=64, verbose_name='Место проведения/Аудитория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время проведения'),
            preserve_default=False,
        ),
    ]
