# Generated by Django 3.1.3 on 2021-01-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210125_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorganizators',
            name='grant',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='стипендия'),
        ),
    ]
