# Generated by Django 3.1.3 on 2021-02-08 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210128_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Картинка мероприятия'),
        ),
        migrations.AddField(
            model_name='organization',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Аватар организации'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Аватар пользователя'),
        ),
        migrations.AlterField(
            model_name='eventorganizators',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='eventorganizators',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Участник'),
        ),
        migrations.AlterField(
            model_name='membersinorganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.organization', verbose_name='организация'),
        ),
        migrations.AlterField(
            model_name='membersinorganization',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
