# Generated by Django 3.1.3 on 2021-02-19 21:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210208_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.AddField(
            model_name='event',
            name='guests',
            field=models.ManyToManyField(related_name='guests', to=settings.AUTH_USER_MODEL, verbose_name='Участники мероприятия'),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(default='organization@example.com', max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(default='+79998887766', max_length=256, validators=[django.core.validators.RegexValidator(message="Phone number is invalid. Try: '+(country code)(number)'. example: +79123456789.", regex='^\\+\\d{10,15}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='social_network_1',
            field=models.URLField(blank=True, verbose_name='ссылка на соцсеть 1'),
        ),
        migrations.AddField(
            model_name='organization',
            name='social_network_2',
            field=models.URLField(blank=True, verbose_name='ссылка на соцсеть 2'),
        ),
        migrations.AddField(
            model_name='user',
            name='education_level',
            field=models.CharField(default='bacalavr', max_length=256, verbose_name='Уровень образования'),
        ),
        migrations.AddField(
            model_name='user',
            name='education_year',
            field=models.CharField(default='', max_length=256, verbose_name='Год обучения'),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.CharField(default='', max_length=256, verbose_name='факультет'),
        ),
        migrations.AddField(
            model_name='user',
            name='fathers_name',
            field=models.CharField(default='', max_length=256, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=256, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='+79998887766', max_length=256, validators=[django.core.validators.RegexValidator(message="Phone number is invalid. Try: '+(country code)(number)'. example: +79123456789.", regex='^\\+\\d{10,15}$')], verbose_name='мобильный телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(default='', max_length=256, verbose_name='Школа'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_1',
            field=models.URLField(default='', verbose_name='ссылка на соц.сеть 1'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_2',
            field=models.URLField(default='', verbose_name='ссылка на соц.сеть 2'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_3',
            field=models.URLField(default='', verbose_name='ссылка на соц.сеть 3'),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default='', max_length=256, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='eventorganizators',
            name='grant',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10, verbose_name='стипендия'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='goal',
            field=models.TextField(default='', verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='mission',
            field=models.TextField(default='', verbose_name='Миссия'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='motivation',
            field=models.TextField(default='', verbose_name='Мотивировка'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='work_trajectory',
            field=models.TextField(default='', verbose_name='Траектория работы'),
        ),
    ]
