# Generated by Django 3.1.3 on 2021-02-26 08:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210220_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='guests',
            field=models.ManyToManyField(blank=True, related_name='guests', to=settings.AUTH_USER_MODEL, verbose_name='Участники мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizators',
            field=models.ManyToManyField(blank=True, through='api.EventOrganizators', to=settings.AUTH_USER_MODEL, verbose_name='Организаторы мероприятия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='education_level',
            field=models.CharField(blank=True, max_length=256, verbose_name='Уровень образования'),
        ),
        migrations.AlterField(
            model_name='user',
            name='education_year',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Год обучения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='факультет'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fathers_name',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=256, validators=[django.core.validators.RegexValidator(message="Phone number is invalid. Try: '+(country code)(number)'. example: +79123456789.", regex='^\\+\\d{10,15}$')], verbose_name='мобильный телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Школа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_1',
            field=models.URLField(blank=True, default='', verbose_name='ссылка на соц.сеть 1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_2',
            field=models.URLField(blank=True, default='', verbose_name='ссылка на соц.сеть 2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_3',
            field=models.URLField(blank=True, default='', verbose_name='ссылка на соц.сеть 3'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Фамилия'),
        ),
    ]
