# Generated by Django 3.1.3 on 2021-02-26 09:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210226_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='goal',
            field=models.TextField(blank=True, default='', verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(blank=True, through='api.MembersInOrganization', to=settings.AUTH_USER_MODEL, verbose_name='участники организации'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='mission',
            field=models.TextField(blank=True, default='', verbose_name='Миссия'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='motivation',
            field=models.TextField(blank=True, default='', verbose_name='Мотивировка'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=256, validators=[django.core.validators.RegexValidator(message="Phone number is invalid. Try: '+(country code)(number)'. example: +79123456789.", regex='^\\+\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='work_trajectory',
            field=models.TextField(blank=True, default='', verbose_name='Траектория работы'),
        ),
    ]
