# Generated by Django 3.1.3 on 2021-02-26 10:30

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210226_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='', validators=[api.validators.ImageResolutionValidator(extensions=['jpg', 'png'], max_height=1600, max_width=1600)], verbose_name='Картинка мероприятия'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='image',
            field=models.ImageField(blank=True, upload_to='', validators=[api.validators.ImageResolutionValidator(extensions=['jpg', 'png'], max_height=1600, max_width=1600)], verbose_name='Аватар организации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='', validators=[api.validators.ImageResolutionValidator(extensions=['jpg', 'png'], max_height=1600, max_width=1600)], verbose_name='Аватар пользователя'),
        ),
    ]
